// Default work photos for the montage
export const WORK_PHOTOS = [
  '/assets/generated/hero-background.dim_1200x600.jpg',
  '/assets/generated/team-photo.dim_1200x800.jpg',
  '/assets/generated/service-home-wiring.dim_800x600.jpg',
  '/assets/generated/service-emergency-repairs.dim_800x600.jpg',
  '/assets/generated/service-fuse-panel-upgrades.dim_800x600.jpg',
  '/assets/generated/service-led-light-fitting.dim_800x600.jpg',
  '/assets/generated/service-appliance-installation.dim_800x600.jpg',
  '/assets/generated/electrical-panel-installation.dim_800x600.jpg',
  '/assets/generated/fan-installation.dim_800x600.jpg',
  '/assets/generated/socket-switch-installation.dim_800x600.jpg',
  '/assets/generated/light-fixture-repair.dim_800x600.jpg',
  '/assets/generated/residential-engineering.dim_800x600.jpg',
  '/assets/generated/commercial-electrical-engineering.dim_800x600.jpg',
  '/assets/generated/electrical-maintenance.dim_800x600.jpg',
  '/assets/generated/cctv-camera-installation.dim_800x600.jpg',
  '/assets/generated/cooler-installation.dim_800x600.jpg',
  '/assets/generated/residential-ac-installation.dim_800x600.jpg',
  '/assets/generated/outdoor-lighting.dim_800x600.jpg',
  '/assets/generated/electrical-fuse-changing.dim_800x600.jpg',
  '/assets/generated/electrical-design.dim_800x600.jpg',
];
